# Generated by Django 4.2.2 on 2023-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='access_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicdata',
            name='allowed_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicdata',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='musicdata',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], max_length=10),
        ),
    ]
